{% set name = "pytube" %}
{% set version = "15.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytube-{{ version }}.tar.gz
  sha256: 076052efe76f390dfa24b1194ff821d4e86c17d41cb5562f3a276a8bcbfc9d1d

build:
  number: 1
  noarch: python
  entry_points:
    - pytube = pytube.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - pytube
    - pytube.contrib
  commands:
    - pip check
    - pytube --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pytube.io/
  license: Unlicense
  license_family: Other
  license_file: LICENSE
  summary: A lightweight, dependency-free Python library (and command-line utility) for downloading YouTube Videos.
  description: |
    pytube is a very serious, lightweight, dependency-free Python library
    (and command-line utility) for downloading YouTube Videos.
  doc_url: https://pytube.io
  dev_url: https://github.com/pytube/pytube

extra:
  recipe-maintainers:
    - jan-janssen
